### ISSUE TITLE
Out of memory problem when compiling VGG-16 model with the puma-compiler.

### ISSUE THREAD

**Issue by frankinwi** [Aayush-Ankit/dpe_emulate#38]
Dear Aayush Ankit,

Thank you for your work.

When I compile the VGG-16 model with the puma-compiler, it crashes due to the constantly increasing memory during the 3rd step `coalescer`, which will finally exceed the physical memory (64GB). But it works fine with the MLP model and single layer test.  

The question is:
(1) Is 64GB memory sufficient to compile the VGG-16 model with the puma-compiler?  
(2) Is there something wrong with the `vgg16.cpp` file which will cause the out of memory problem?

Thank you in advance!
Frank.

**Comment by negishubham** [comment]
Hi Frank, 

Thanks for the question. 
The CNN models in puma compiler use loop unrolling to perform the MVMU operation which requires more memory. Hence, to run the PUMA tool for CNN we run it layer by layer and add the performance (energy, latency) numbers for all the layers to get the performance for the whole CNN. Also, MLP is working fine because it doesn't use loop unrolling to perform the MVMU operation. So if you want to run the vgg16 on PUMA please use the conv-layer.cpp model file to run each layer on PUMA. Also, the vgg16.cpp file is given as an example as to how to write a model file in the puma compiler. 

Thanks,
Shubham

**Comment by frankinwi** [comment]
@gustahrodrigues, thank you very much for your reply. It helps me a lot!

Thanks!
Frank

**Comment by Aayush-Ankit** [comment]
Thanks @frankinwi for your interest in our work, and thanks @negishubham for helping with this issue 👍.

**Comment by frankinwi** [comment]
@Aayush-Ankit @negishubham I used the following `conv-layer.cpp` model file to run on PUMA 

    #include <assert.h>
    
    #include <string>
    
    #include <vector>
    
    #include "puma.h"
    
    #include "conv-layer.h"
    
    int main(int argc, char** argv) {

        Model model = Model::create("conv-layer");
    
        // Process parameters
        unsigned int in_size_x = 28;
        unsigned int in_size_y = 28;
        unsigned int in_channels = 3;
        unsigned int out_channels = 32;
        unsigned int k_size_x = 3;
        unsigned int k_size_y = 3;
        if(argc == 7) {
            in_size_x = atoi(argv[1]);
            in_size_y = atoi(argv[2]);
            in_channels = atoi(argv[3]);
            out_channels = atoi(argv[4]);
            k_size_x = atoi(argv[5]);
            k_size_y = atoi(argv[6]);
        }
    
        // Input stream
        auto in_stream = InputImagePixelStream::create(model, "in_stream", in_size_x, in_size_y, in_channels);
    
        // Output stream
        unsigned int out_size_x = in_size_x;
        unsigned int out_size_y = in_size_x;
        auto out_stream = OutputImagePixelStream::create(model, "out_stream", out_size_x, out_size_y, out_channels);
    
        // Layer
        out_stream = conv_layer(model, "", k_size_x, k_size_y, in_size_x, in_size_y, in_channels, out_channels, in_stream);
    
        // Compile
        model.compile();
    
        // Destroy model
        model.destroy();
    
        return 0;

}

And there is a segment fault which indicates that the code in `regalloc.cpp line 440-461` calls`liveNow.erase(spillCandidate);` to remove an element in liveNow which is a set container in the for loop, and it causes the dereference of NULL pointer in the next loop.

>     Starting program: /home/frank/PycharmProjects/puma-compiler/test/conv-layer.test 
>     Partitioning graph... done.
>     Physical layout... finishdone.
>     Memory allocation... done.
>     MVM coalescing... done.
>     Linearizing graph... done.
>     Register allocation... 
>     Program received signal SIGSEGV, Segmentation fault.
>     0x00007ffff7b44881 in RegisterAllocator::allocateRegistersWithSpilling (this=0x555556514e80, length=32, allocator=..., liveNow=std::set with 47 elements = {...}, 
>         spillTracker=..., spillAddressReg=1536, coreOperationList=std::__cxx11::list = {...}, op=0x55555586afd8) at regalloc.cpp:442
>     442	                unsigned int address = memoryAllocator_->memalloc(partitioner_->getVTile(spillCandidate), spillCandidate->length());
>     (gdb) 

Could you give more details of how to complie a single conv layer with puma-complier.

**Comment by negishubham** [comment]
Hi Frank, 

Thanks for the question. 
As I can see in your model file you have changed the FM size to 28x28. So this FM size also leads to a similar issue of requiring high memory due to loop unrolling. So what I would suggest is to use a small FM size. We have tested with all the big CNNs and a FM size of 9x9 works pretty well. Now to get the actual performance numbers please use the below scaling factor: 

**Scaling Factor**: Let's say you are using X, Y as FM size for your simulations in PUMA then you should scale your latency and energy by ((X_actual+2p)/(X+2p))^2 where  X_actual is the actual FM size in the NN model and p is the padding.

Also, we have provided some test scripts in **test/utils/** folder so please try to run those as a sanity check to if you have setup the simulator correctly or not. Before running the script please change the branch in the puma compiler to stride-support. You can also use these scripts to run different configurations as well by changing appropriate variables. 

Thanks,
Shubham

**Comment by frankinwi** [comment]
Hi @negishubham,

Thanks for your advice.
I followed your instruction and downloaded the [puma compiler(stride-support branch)](https://github.com/Aayush-Ankit/puma-compiler/tree/stride-support), which is different from [the original version](https://github.com/illinois-impact/puma-compiler), and it works fine with CNN single layer and MLP model.

Thanks,
Frank

**Comment by negishubham** [comment]
Glad to hear that it worked for you!

Thanks,
Shubham
