### ISSUE TITLE
Questions about num_inputs

### ISSUE THREAD

**Issue by FrankWu1998** [Aayush-Ankit/dpe_emulate#43]
When I change the num_inputs in test/testasm/mlp/input.py, the command "python dpe.py -n mlp" gives the same result. Is this reasonable? why?

**Comment by FrankWu1998** [comment]
The input size and output size of mlp-l4-mnist are 784 and 10 respectively, but why the output in output.txt is 210 values?

**Comment by leibo-hust** [comment]
@FrankWu1998 Hi, were you able to run the **mlp** model successfully? I followed the steps given, but I keep having some minor problems. Is there anything that needs attention or modification?

Thanks

**Comment by FrankWu1998** [comment]
@leibo-hust I ran **mlp** successfully because I followed every step in how_to_run.md.

**Comment by leibo-hust** [comment]
@FrankWu1998 I also followed every step in **how_to_run.md** and tried many times, but had problems. I'm using the latest version, how about you?

**Comment by FrankWu1998** [comment]
@leibo-hust Yes, I use the latest branch "training". I think you only need to follow the steps in how_to_run.md exactly. It should be noted that I chose the i_mvm function as shown in the figure below. 
![image](https://user-images.githubusercontent.com/47807914/112241574-7b2cba80-8c85-11eb-8eed-b1386a45cd1f.png)

**Comment by leibo-hust** [comment]
@FrankWu1998 Thank you very much. I checked and I use this _i_mvm_ as well. Amazingly, I just executed it again from scratch without making any changes and I got the following error that I never encountered before. Then I changed _num_tile_compute_ in **config.py** to **4** (I used **5** before because I think there were 5 tiles starting from 0 to 4) and it actually executed successfully.
![image](https://user-images.githubusercontent.com/63854353/112244034-939ed400-8c89-11eb-97af-7c90155185ec.png)

Finally I found out that I can't use the **-t** argument, either **-t 4** or **-t 5** will be wrong. We should just use **python dpe.py -n mlp**.

**Comment by FrankWu1998** [comment]
@leibo-hust It is my pleasure. As far as I know, there are two tiles used for input and output, and the remaining tiles are used to configure DNN, so you need to pay attention to this. I think num_tiles should depend on the size of the DNN, but I am not very sure.

**Comment by leibo-hust** [comment]
@FrankWu1998 Yes, you are right. **num_tiles_compute** depends on the size of the NN. I think it should also be related to the number of nodes per layer and the size of the tile. 
I just compared the results of runs with different **num_tile_compute** values and the results are the same.
